version: '3.9'
services:
    jenkins-docker:
       image: docker:dind
       container_name: jenkins-docker
       restart: on-failure
       privileged: true
       environment: 
         - DOCKER_TLS_CERTDIR=/certs
       volumes: 
         - jenkins-data:/var/jenkins_home
         - jenkins-docker-certs:/certs/client
       networks: 
        minikube:
          aliases:
            - dind
       ports: 
         - 2376:2376

    jenkins-blueocean:
       build: .
       image: myjenkins
       container_name: jenkins
       restart: on-failure
       environment: 
         - DOCKER_HOST=tcp://docker:2376
         - DOCKER_CERT_PATH=/certs/client
         - DOCKER_TLS_VERIFY=1
       volumes: 
         - jenkins-data:/var/jenkins_home
         - jenkins-docker-certs:/certs/client:ro
       networks: 
        - minikube
       ports: 
         - 8080:8080
         - 50000:50000
       depends_on:
        - jenkins-docker

volumes:
  jenkins-data:
  jenkins-docker-certs:
networks:
  minikube:
    external: true