apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ctfd-ingress
  labels:
    name: ctfd-ingress
  namespace: ctfd-space
spec:
  rules:
  - host: localhost
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: ctfd
            port: 
              number: 8000
