apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mysql.volume.name }}
  namespace: {{ .Values.mysql.volume.namespace }}
spec:
  resources:
    requests:
      storage: {{ .Values.mysql.volume.spec.resources.storage }}
  accessModes:
   - {{ .Values.mysql.volume.spec.accessModes }}
