apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysql.secret.name }}
  namespace: {{ .Values.mysql.secret.namespace }}
type: Opaque
data:
{{- range .Values.mysql.secret.data }}
  {{ .key }}: {{ .value }}
{{- end}}
  
