apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.service.name }}
  namespace: {{ .Values.mysql.service.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.mysql.name }}
  ports:
  - port: {{ .Values.mysql.service.ports.port }}
    targetPort: {{ .Values.mysql.service.ports.targetPort }}
