apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: ctfd-space
spec:  
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
        name: mysql
    spec:
      containers:
        - image: mysql:5.7
          name: mysql
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: mysql-pass
                    key: password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DATABASE
          ports:
            - containerPort: 3306
          volumeMounts:
          - name: mysql-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
