

adminer:
  name: adminer
  namespace: ctfd-space
  container:
    name: adminer
    image: adminer
    ports:
      containerPort: 8080
    resources:
      limits:
        memory: "128Mi"
        cpu: "256m"
    readinessProbe:
      scheme: HTTP
      path: http://0.0.0.0/
      port: 8080
      initialDelaySeconds: 10
      periodSeconds: 5
  ingress: 
    name: adminer-ingress
    host: localhost
    path: /adminer
    service:
      name: adminer
      port:
        number: 8080