

adminer:
  name: adminer
  namespace: ctfd-space
  container:
    name: adminer
    image: adminer
    ports:
      containerPort: 8080
    resources:
      limits:
        memory: "128Mi"
        cpu: "256m"
  ingress: 
    name: adminer-ingress
    host: localhost
    path: /adminer
    service:
      name: adminer
      port:
        number: 8080